<%@ Page Title="" Language="C#"
    MasterPageFile="~/Administration/Administration.master"
    AutoEventWireup="true" CodeBehind="StoriesPanel.aspx.cs"
    Inherits="PayItForward.WebForms.Administration.StoriesPanel" %>

<%@ Register Src="~/Controls/Pager/LinkPager.ascx" TagName="LinkPager" TagPrefix="custom" %>

<asp:Content ID="StoriesContent" ContentPlaceHolderID="AdminContent" runat="server">
    <asp:UpdatePanel runat="server" ID="UpdateGridPanel">
        <ContentTemplate>

            <asp:GridView ID="GridViewStories" runat="server"
                SelectMethod="GridViewStories_GetData"
                UpdateMethod="GridViewStories_UpdateItem"
                DeleteMethod="GridViewStories_DeleteItem"
                ItemType="PayItForward.Data.Models.Story"
                AllowPaging="True" PagerSettings-Visible="false"
                PageSize="5"
                AllowSorting="True"
                DataKeyNames="Id"
                MultipleActiveResultSets="true"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true"
                AutoGenerateColumns="false"
                CssClass="bordered hoverable striped">

                <Columns>
                    <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                    <asp:BoundField DataField="GoalAmount" HeaderText="GoalAmount" SortExpression="GoalAmount" />
                    <asp:BoundField DataField="CollectedAmount" HeaderText="CollectedAmount" SortExpression="CollectedAmount" />
                    <asp:BoundField DataField="ExpirationDate" HeaderText="ExpirationDate" SortExpression="ExpirationDate" />
                    <asp:BoundField DataField="Category.Name" HeaderText="Category" SortExpression="Category.Name" />
                    <asp:BoundField DataField="IsAccept" HeaderText="IsAccept" SortExpression="IsAccept" ReadOnly="true" />
                </Columns>
            </asp:GridView>
        </ContentTemplate>
    </asp:UpdatePanel>
    <br>
    <div class="row">
        <div class="col s3 offset-s3">
            <custom:LinkPager ID="custlinkPager" runat="server" OnPageChanged="custLinkPager_PageChanged" />
        </div>
    </div>
    <br>
    <br>
    <br>
</asp:Content>
