<%@ Page Title="" Language="C#"
    MasterPageFile="~/Administration/Administration.master"
    AutoEventWireup="true" CodeBehind="UsersPanel.aspx.cs"
    Inherits="PayItForward.WebForms.Administration.UsersPanel" %>

<%@ Register Src="~/Controls/Pager/Pager.ascx" TagPrefix="custom" TagName="Pager" %>


<asp:Content ID="UserContent" ContentPlaceHolderID="AdminContent" runat="server">
    <asp:UpdatePanel runat="server" ID="UpdateGridPanel">
        <ContentTemplate>

            <asp:GridView ID="GridViewUsers" runat="server"
                SelectMethod="GridViewUsers_GetData"
                UpdateMethod="GridViewUsers_UpdateItem"
                DeleteMethod="GridViewUsers_DeleteItem"
                ItemType="PayItForward.Data.Models.User"
                AllowPaging="True" PagerSettings-Visible="false"
                PageSize="5"
                AllowSorting="True"
                DataKeyNames="Id"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true"
                AutoGenerateColumns="false"
                CssClass="bordered hoverable striped">

                <Columns>
                    <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                </Columns>
            </asp:GridView>
        </ContentTemplate>
    </asp:UpdatePanel>
    <div class="row">
        <div class="col s6">
            <custom:Pager ID="custPager" runat="server" OnPageChanged="custPager_PageChanged" />
        </div>
       
    </div>
    <br>
    <br>
    <br>
    <script>
        $(document).ready(function () {
            $('select').material_select();
        });
    </script>
</asp:Content>
